name: flutter_account_kit
description: A Flutter plugin for allowing users to authenticate with the native Android &amp; iOS AccountKit SDKs
version: 0.6.0
author: Onyemaechi Okafor <peerwaya@yahoo.com>
homepage: https://github.com/peerwaya/flutter-account-kit

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

dev_dependencies:
  flutter_test:
    sdk: flutter
    
# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.peerwaya.flutteraccountkit
    pluginClass: FlutterAccountKitPlugin

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
  flutter: ">=0.11.3 <2.0.0"